apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ahmedbouzid07/test-sops.git'
    targetRevision: HEAD
    path: '.'   # path to your helmfile.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ahmed-playground
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
